services:
  ingestor:
    container_name: ingestor
    env_file:
      - './ingestor/.env'
    build:
      context: './ingestor/vendor/laravel/sail/runtimes/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
    image: 'sail-8.4/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8081:80'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - './ingestor/:/var/www/html'
      - './database.sqlite:/var/www/html/database/magnum.sqlite'
    networks:
      - magnum
    depends_on:
      - redis
  initiator:
    env_file:
      - './initiator/.env'
    container_name: initiator
    build:
      context: './initiator/vendor/laravel/sail/runtimes/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP-1000}'
    image: 'sail-8.4/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8082:80'
    environment:
      WWWUSER: '${WWWUSER-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - './initiator/:/var/www/html'
      - './database.sqlite:/var/www/html/database/magnum.sqlite'
    networks:
      - magnum
    depends_on:
      - redis
  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'magnum-redis:/data'
    networks:
      - magnum
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
networks:
  magnum:
    name: magnum
    driver: bridge
volumes:
  magnum-redis:
    name: magnum-redis
    driver: local
